--début tp
--création de la table 
CREATE TABLE clients (
    client_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nom VARCHAR2(50) NOT NULL,
    prenom VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE,
    telephone VARCHAR2(20),
    adresse VARCHAR2(200),
    PRIMARY KEY (client_id)
);
