--executer en tant qu'utilisateur SYS
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO tpl2 IDENTIFIED BY oracle;
GRANT CREATE VIEW, CREATE JOB, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE ANY CONTEXT TO tpl2;
ALTER USER tpl2 DEFAULT TABLESPACE users;
ALTER USER tpl2 TEMPORARY TABLESPACE temp;