create or replace package test_client_api is

   -- generated by utPLSQL for SQL Developer on 2024-11-03 18:49:01
/**
     * Suite de tests pour les fonctionnalités du package client_API.
     * Définit le chemin de la suite pour l'exécution des tests unitaires.
     * @suite test_client_api
     * @suitepath alltests
     */

    /**
     * Test de la fonction ins_client.
     * Vérifie que l'insertion d'un client dans la table clients fonctionne correctement avec des valeurs valides.
     */

   procedure ins_client;
 /**
     * Test de la fonction ins_client avec un nom NULL.
     * Vérifie que l'insertion échoue lorsqu'un nom NULL est fourni, en validant la contrainte NOT NULL.
     * Ce test simule une erreur intentionnelle pour valider le comportement attendu.
     * @test_description insertion d'un client avec nom NULL, entraîne une erreur de contrainte.
     */
    PROCEDURE ins_client_null;
    
     /**
     * Test de la fonction upd_client.
     * Vérifie que la mise à jour des informations d'un client existant fonctionne correctement.
     */
   procedure upd_client;
/**
     * Test de la fonction del_client.
     * Vérifie que la suppression d'un client dans la table clients fonctionne correctement.
     */
   procedure del_client;
 /**
     * Test de la fonction get_client.
     * Vérifie que la récupération des informations d'un client existant par son ID fonctionne correctement.
     */
   procedure get_client;

end test_client_api;
