create or replace package test_client_api is

   -- generated by utPLSQL for SQL Developer on 2024-11-03 18:49:01

   --%suite(test_client_api)
   --%suitepath(alltests)

   --%test
   procedure ins_client;

   --%test
   procedure upd_client;

   --%test
   procedure del_client;

   --%test
   procedure get_client;

end test_client_api;