-- Taha Abdelmoumen (2202351)
-- Script de création de la table commande

CREATE TABLE commande (
    commande_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    client_id NUMBER NOT NULL,
    date_commande DATE NOT NULL,
    prix_total NUMBER(10, 2),
    status VARCHAR2(20) DEFAULT 'En attente',
    PRIMARY KEY (commande_id)
);

-- Ajout de la contrainte de clé étrangère pour établir une relation
-- entre la table client et la table commande.
ALTER TABLE commande
ADD CONSTRAINT fk_client
FOREIGN KEY (client_id)
REFERENCES clients(client_id);

INSERT INTO commande (client_id, date_commande, prix_total, status) VALUES
(1, SYSDATE, 250.00, 'En cours'),
(2, SYSDATE, 149.99, 'Livrée'),
(3, SYSDATE, 323.00, 'Annulée'),
(4, SYSDATE, 75.75, 'En attente'),
(5, SYSDATE, 500.49, 'En cours');

-- tests unitaires pour toutes les commandes.
BEGIN
    ut.run('test_commande_api'); 
END;